### ISSUE TITLE
dismissHandler() getting called twice.

### ISSUE THREAD

**Issue by SirVeryBritish** [scihant/CTShowcase#9] opened 2017-07-15 16:21 UTC
First of all, thank you so much for this project. It saved myself a lot of time! During integration into my current project I found some weird behaviour, which I would label a bug. 

In my projects I have two UINavigationController, the first one being "the base of operation", the second one comes from the top like a curtain with some UIViewController on it's stack. On the second one I'm using your CTShowcaseViews as a chain, for a tutorial like:

````swift
let showcase = CTShowcaseView(title: "title", message: "message",
key: nil) { () -> () in
//chained CTShowcaseViews
}
````

Everything goes as expected UNTIL the end, where I call for a closing transition which moves the second UINavigationController together with its UIViewControllers from the screen, moving direction upwards. Some CTShowcaseViews handlers invoked again and since I used them as a chain, you can imagine what a mess it was to have the animation on the UIViewControllers from the first UINavigationController, actually I was impressed that it did not crash.

After debugging I have the theory, since I use a transition, which calls dismiss on the top UIViewController from the second UINavigationController, that this invokes the dismiss() again in the CTShowcaseView. Since the dismissHandler didn't get cleared earlier, it's calling it again.

I propose this change, to prevent the dismissHandler from being called twice in such situations:

````swift

@objc open class CTShowcaseView: UIView {
//...
    open func dismiss() {
        UIView.animate(withDuration: CTGlobalConstants.DefaultAnimationDuration, animations: { () -> Void in
            self.alpha = 0
        }, completion: { (finished) -> Void in
            self.removeFromSuperview()
            self.dismissHandler?()
            self.dismissHandler = nil //clears the dismissHandler, after being invoked once.
        })
    }
//...
}
````

**Comment by scihant** [comment] 2017-07-15 17:44
Thanks for the feedback and the pull request. 
There are only two cases that might cause the dismiss handler to get called:

- The user taps on the showcase
- The user creates a showcase with a visible region that's less than %75 of the total area of the showcase. 

This means that dismissing a ViewController stack with or without any animation shouldn't cause the dismiss handler to be called. But you're saying that it gets called, which makes me wonder the exact scenario that causes this behavior.  Would it be possible for you to send me a bare-bones project that  demonstrates this problem? Your pull request would certainly solve it, but I think it would be better if I could take a detailed look and find out the root cause of the problem because it might be causing other problems as well. 

Right now it seems that it shouldn't have happened in the first place. If I don't find a root cause that requires a more complicated fix, I'll merge your pull request since it won't break anything anyway.

Thanks.

**Comment by SirVeryBritish** [comment] 2017-07-18 14:09
Hey mate, 
Thanks for the quick reply, I will be busy the next two weeks, but I’ve set me a reminder to investigate this and make a MVP to show you the behaviour.

Regards,
Dominic Schablas

**Comment by scihant** [comment] 2017-08-13 18:52
Any update on this?

**Comment by SirVeryBritish** [comment] 2017-08-16 16:23
Sorry for the long waiting time. I had some stressful weeks. I'm currently trying to extract the code from the project in my free time, without revealing too much. I will provide you latest next weekend with a working project to analyse the behaviour.

UPDATE:
Okay, I've spent some hours to scrap the most essential code from our project and test it with CTShowcase 2.1. Guess what, the handler is not getting called twice, huh. So either the problem is either happening because of our complex navigation structure or some other artefact, which happens during the animated transitions. My guess goes now with the first one. From my side, we can close this ticket, I don't see how this issue can come from your pod.

**Comment by scihant** [comment] 2017-08-29 07:20
Ok, thanks for getting back to me. I'll close the issue for now. If, in the future, you see something like this again in another context, we can always revisit it.

Thanks again.

**Closed as completed by scihant** 2017-08-29 07:20 UTC
